---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: argocd-rollout
spec:
  type: LoadBalancer
  selector:
    app: nginx-rollout
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: nginx-rollout
  namespace: argo-rollout
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-rollout
  template:
    metadata:
      labels:
        app: nginx-rollout
    spec:
      containers:
        - name: nginx
          image: asia-south1-docker.pkg.dev/praveen-345/argocd-rollout/nginx:latest  # <-- This gets replaced by GitHub Action with version
          ports:
            - containerPort: 80
  strategy:
    canary:
      steps:
        - setWeight: 20
        - pause: { duration: 180 }
        - setWeight: 50
        - pause: { duration: 180 }
        - setWeight: 100
