apiVersion: v1
kind: Namespace
metadata:
  name: argocd-rollout
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: argocd-rollout
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080  # optional, must be between 30000-32767 if you set it

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: argocd-rollout
  labels:
    app: nginx
    updated-by: "asif-0707"  # ✅ Added label to trigger sync
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.25-1
          ports:
            - containerPort: 80
          env:                # ✅ Dummy env var to trigger sync
            - name: DUMMY_ENV
              value: "07"



