apiVersion: v1
kind: Namespace
metadata:
  name: argocd-rollout
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: argocd-rollout
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: argocd-rollout
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.25  # Use any public image you prefer
          ports:
            - containerPort: 80

