name: Build and Push Docker Image to GCP Artifact Registry

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: as-gke
  PROJECT_NUMBER: 4816
  REGION: asia-south1
  REPOSITORY: artifact-gke-wif
  REPOSITORY_REGION: asia-south1
  CLUSTER: test-prvt
  CLUSTER_ZONE: asia-south1-a
  IMAGE_NAME: nginx

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to GCP using Workload Identity Federation
        id: auth
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: projects/48155601516/locations/global/workloadIdentityPools/artifact-gke-wif/providers/github
          service_account: artifact-gke@asgke.iam.gserviceaccount.com

      - name: Configure gcloud
        run: |
          gcloud config set project $PROJECT_ID
          gcloud auth configure-docker $REPOSITORY_REGION-docker.pkg.dev

      - name: Build Docker image
        run: |
          docker build -t
          asia-south1-docker.pkg.dev/asif-praveen-gke/artifact-gke/$IMAGE_NAME:latest

      - name: Push Docker image to Artifact Registry
        run: |
          docker push
          asia-south1-docker.pkg.dev/asif-praveen-gke/artifact-gke/$IMAGE_NAME:latest

      - name: Update rollout.yaml with new image tag
        run: |
          sed -i "s|image:.*|image: ${{ steps.vars.outputs.image_uri }}|" nginx-rollout/rollout.yaml
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add nginx-rollout/rollout.yaml
          git commit -m "Update rollout.yaml to ${{ steps.vars.outputs.image_uri }}"
          git push
